### ISSUE TITLE
[Typo] 크기를 기준으로 필터링 관련 소스코드 예시, 책의 본문 p.32

### ISSUE THREAD

**Issue by raulandres-sz** [gilbutITbook/007028#2]
책에서 소스코드 예시가 잘못 삽입되어 있습니다.

본문 32쪽 하단을 살펴보면, 

> ... 크기를 기준으로 한 필터링 기능도 구현해달라는 요구사항 ...
>
> ...
> 
> ```cpp
> ProjuctFilter::Items ProjuctFilter::by_color(Items items, const Color color)
>   {
>     Items result;
>     for (auto& i : items)
>       if (i->color == color)
>         result.push_back(i);
>     return result;
>   }
> ```
>

위 코드에서 `Color` 관련된 키워드를 `Size`로 바꾸셔야 할 것 같습니다.

**Comment by ronykwon** [comment]
넵 맞습니다.
확인해 보니 원서에 오류가 있었습니다.
아래와 같이 수정 되어야 합니다.

감사합니다.

ProjuctFilter::Items ProductFilter::by_size(Items items, const Size size)
  {
    Items result;
    for (auto& i : items)
      if (i->size == size)
        result.push_back(i);
    return result;
  }
